version: '3'
services: 
    app:
        image: "node:12-alpine"
        working_dir: /home/node/app
        volumes: 
            - .:/home/node/app
        environment:
            - NODE_ENV=production
            - PORT=5432
            - HELLO_MESSAGE="Node message for you"
        ports:
            - "80:5432"
        command: "npm start"

    app2:
        image: "node:12-alpine"
        working_dir: /home/node/app
        volumes: 
            - .:/home/node/app
        environment:
            - NODE_ENV=production
            - PORT=1234
            - HELLO_MESSAGE="Another Node message"
        ports:
            - "8080:1234"
        command: "npm start"
    